# NumPy Exercises 


## Defining an array


#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [3]:
array1=np.ones(10)
print(array1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 tens

In [4]:
array2=np.full(10, 10)
print(array2)

[10 10 10 10 10 10 10 10 10 10]


#### Create an array of the integers from 10 to 100

In [5]:
array3=np.linspace(10,100,91)
print(array3)

[ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22.  23.
  24.  25.  26.  27.  28.  29.  30.  31.  32.  33.  34.  35.  36.  37.
  38.  39.  40.  41.  42.  43.  44.  45.  46.  47.  48.  49.  50.  51.
  52.  53.  54.  55.  56.  57.  58.  59.  60.  61.  62.  63.  64.  65.
  66.  67.  68.  69.  70.  71.  72.  73.  74.  75.  76.  77.  78.  79.
  80.  81.  82.  83.  84.  85.  86.  87.  88.  89.  90.  91.  92.  93.
  94.  95.  96.  97.  98.  99. 100.]


#### Create an array of all the odd integers from 10 to 30

In [6]:
array4=np.arange(11,30,2)
print(array4)

[11 13 15 17 19 21 23 25 27 29]


#### Create a 3x3 array with values ranging from 0 to 8 

In [7]:
array5=np.array([[0,1,2],[3,4,5], [6,7,8]])
print(array5)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create an array of 25 random numbers between 0 and 1

In [8]:
array6 = np.random.rand(25)
print(array6)

[0.40451311 0.16956456 0.91622205 0.77307166 0.67376751 0.58995991
 0.07002511 0.46763124 0.50396112 0.23478143 0.24974652 0.52457226
 0.94592309 0.58539456 0.40007719 0.0233225  0.55446056 0.92998159
 0.28927603 0.85120123 0.62000906 0.36017052 0.23241255 0.32571892
 0.0970357 ]


#### Create an array of 40 linearly spaced points between 0 and 10:

In [9]:
array7=np.linspace(0,10,40)
print(array7)

[ 0.          0.25641026  0.51282051  0.76923077  1.02564103  1.28205128
  1.53846154  1.79487179  2.05128205  2.30769231  2.56410256  2.82051282
  3.07692308  3.33333333  3.58974359  3.84615385  4.1025641   4.35897436
  4.61538462  4.87179487  5.12820513  5.38461538  5.64102564  5.8974359
  6.15384615  6.41025641  6.66666667  6.92307692  7.17948718  7.43589744
  7.69230769  7.94871795  8.20512821  8.46153846  8.71794872  8.97435897
  9.23076923  9.48717949  9.74358974 10.        ]


## Indexing 


In [10]:
#You are given the following 2D array
a = np.arange(1,25).reshape(4,-1)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [11]:
# Use array indexing to select the subset that contains 9,10,11,12,15,16,17,18,21,22,23,24. 
# In other words, the 3 * 4 sub-matrix in the bottom right corner of your array
# I have shown you the output -- be careful, if you run your code, it is going to "wipe out" my output
a = np.arange(1,25).reshape(4,-1)
a[1:4,2:6]

array([[ 9, 10, 11, 12],
       [15, 16, 17, 18],
       [21, 22, 23, 24]])

In [12]:
# Use array indexing  get the value 20, as my output shows
a = np.arange(1,25).reshape(4,-1)
print(a[3,1])

20


In [13]:
# Use array indexing  get the column 10, 16, 22, as my output shows
a = np.arange(1,25).reshape(4,-1)
a[1:4,3:4]


array([[10],
       [16],
       [22]])

In [14]:
# Use array indexing  get the row [15,16,17] as my output shows
a = np.arange(1,25).reshape(4,-1)
a[2,2:5]

array([15, 16, 17])

### Now the hard task!

#### Write a function that gives the users four random integers between 1 and 10 and ask them to enter the square number of them. If the user answers all of them correctly, congratulate them. Otherwise, show them the right answer

In [26]:
# Step 0: Import numpy -- ALWAYS import all the libraries you need at the beginning!
import numpy as np

#Step 1: Function creation -- refer to the last lab for the syntax of function creation
# does our function take parameters?
# Create your function here:
def square_num():
    
#Step 2: Create an array of four random integers between 1 and 10 

    array=np.random.randint(1,10,4)
   
#Step 3: Print your numbers

    print(array)


#Step 4: Prompt the user to enter four numbers, ONE AT A TIME. Use a loop to store these four numbers in a new array
#  HINT 1: We could take all four numbers in through one line, but to practice loop, let's do it the hard way
#  HINT 2: You can start by creating an empty array -- np.array([]), then appending to it one at a time
#  HINT 3: Remember, input() only returns STRINGS. You need to turn them into integers
    enter=np.array([])
    for i in range(0,4):
        print("Enter the square of: "+str(array[i]))
        x=input()
        enter=np.append(enter, int(x))
        i+=1




#Step 5: Now that you have the two arrays, you can compare them using array functions and decide whether the answers are correct
#  HINT 4: To compare two arrays, you can use array1 == array2 -- however, you have to use a variable to hold the result
#          The resulted array is an array of Boolean values. To quickly check whether it contains true value, you might want to
#          use the all() or any() function...

    array=np.square(array)
    enter=enter.astype(int)
    if (array==enter).all():
        print("You got them all correct!")
    else:
        print("You got one or more wrong. Here are the answers: ")
        print(array)

    

In [27]:
square_num()

[3 8 3 8]
Enter the square of: 3
9
Enter the square of: 8
64
Enter the square of: 3
9
Enter the square of: 8
9
You got one or more wrong. Here are the answers: 
[ 9 64  9 64]
